spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver 
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
  redis:
    host: localhost
    port: 6379

#logging:
#  config: classpath:logback-spring.xml

logging:
  config: classpath:log4j2-spring.xml
  
defineValue: chenhan

#日志打印自动配置报告    
#debug: true


#actuator 配置
management:
  endpoints:
    web:
      base-path: /   #将/actuator/info调整为/info接口
      exposure:
        include: "*"